# Generated by Django 4.2 on 2023-04-30 14:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_influencer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='state',
            field=models.CharField(choices=[('AL', 'Alabama, USA'), ('AK', 'Alaska, USA'), ('AZ', 'Arizona, USA'), ('AR', 'Arkansas, USA'), ('CA', 'California, USA'), ('CO', 'Colorado, USA'), ('CT', 'Connecticut, USA'), ('DE', 'Delaware, USA'), ('FL', 'Florida, USA'), ('GA', 'Georgia, USA'), ('HI', 'Hawaii, USA'), ('ID', 'Idaho, USA'), ('IL', 'Illinois, USA'), ('IN', 'Indiana, USA'), ('IA', 'Iowa, USA'), ('KS', 'Kansas, USA'), ('KY', 'Kentucky, USA'), ('LA', 'Louisiana, USA'), ('ME', 'Maine, USA'), ('MD', 'Maryland, USA'), ('MA', 'Massachusetts, USA'), ('MI', 'Michigan, USA'), ('MN', 'Minnesota, USA'), ('MS', 'Mississippi, USA'), ('MO', 'Missouri, USA'), ('MT', 'Montana, USA'), ('NE', 'Nebraska, USA'), ('NV', 'Nevada, USA'), ('NH', 'New Hampshire, USA'), ('NJ', 'New Jersey, USA'), ('NM', 'New Mexico, USA'), ('NY', 'New York, USA'), ('NC', 'North Carolina, USA'), ('ND', 'North Dakota, USA'), ('OH', 'Ohio, USA'), ('OK', 'Oklahoma, USA'), ('OR', 'Oregon, USA'), ('PA', 'Pennsylvania, USA'), ('RI', 'Rhode Island, USA'), ('SC', 'South Carolina, USA'), ('SD', 'South Dakota, USA'), ('TN', 'Tennessee, USA'), ('TX', 'Texas, USA'), ('UT', 'Utah, USA'), ('VT', 'Vermont, USA'), ('VA', 'Virginia, USA'), ('WA', 'Washington, USA'), ('WV', 'West Virginia, USA'), ('WI', 'Wisconsin, USA'), ('WY', 'Wyoming, USA')], max_length=2),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reference_no', models.IntegerField(db_index=True, unique=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)])),
                ('report_ready', models.BooleanField(default=False)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.influencer')),
            ],
        ),
    ]
