# Generated by Django 4.2 on 2023-04-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_influencer_state_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
