# Generated by Django 4.2 on 2023-04-30 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_business_end_date_alter_business_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='reference_no',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
