# Generated by Django 4.2 on 2023-05-11 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_business_type_of_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='influencer',
        ),
        migrations.CreateModel(
            name='BusinessInfluencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.business')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.influencer')),
            ],
        ),
    ]
