# Generated by Django 4.2 on 2023-05-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_remove_business_influencer_businessinfluencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='influencer',
            field=models.ManyToManyField(to='user_management.influencer'),
        ),
    ]
