# Generated by Django 4.2 on 2023-05-11 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_business_influencer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='influencer',
        ),
        migrations.DeleteModel(
            name='BusinessInfluencer',
        ),
        migrations.AddField(
            model_name='business',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.influencer'),
        ),
    ]
