# Generated by Django 4.2 on 2023-05-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_remove_business_influencer_delete_businessinfluencer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='influencer',
        ),
        migrations.AddField(
            model_name='business',
            name='influencer_association',
            field=models.ManyToManyField(blank=True, to='user_management.influencer'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='business_association',
            field=models.ManyToManyField(blank=True, to='user_management.business'),
        ),
    ]
